server:
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:mysql://localhost:3310/remedios_api?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none # Alterado para none para evitar conflito com Flyway
    show-sql: true   # Útil para debug
  flyway:
      enabled: true
      clean-disabled: false  # Habilita a operação clean
      locations: classpath:db/migration
      baseline-on-migrate: true
      repair-on-migrate: true
      validate-on-migrate: true
      clean-on-validation-error: true